// Liste des pays livrables (ISO2 + libellé FR) — partagée entre le sélecteur pays du
// checkout (CheckoutForm.tsx) et le formulaire de correction d'adresse de l'admin
// (admin/orders/[id]/page.jsx), pour n'avoir qu'un seul endroit à maintenir.
//
// Couverture Chrono Express Shopper Max+ (contrat 17895404) : 228 pays et territoires
// (les 2 seuls pays non desservis par Chronopost — Corée du Nord, Turkménistan — sont
// exclus) + la France. Généré à partir du "Zoning international pour Chrono Express et
// Chrono Classic" fourni par Chronopost (fichiers dans wybob-documents/).
//
// Exclusion supplémentaire par mesure de précaution (sanctions internationales, zones de
// conflit majeur, risque logistique élevé) : Afghanistan, Biélorussie, République
// Centrafricaine, Haïti, Iran, Kiribati, Libye, Nauru, Russie, Soudan, Somalie, Syrie,
// Tuvalu, Ukraine, Yémen.
//
// Cette liste doit rester synchronisée avec COUNTRY_SHIPPING dans shipping/zones.ts (mêmes pays).
export const COUNTRY_OPTIONS = [
  { code: "FR", label: "France" },
  { code: "ZA", label: "Afrique du Sud" },
  { code: "AL", label: "Albanie" },
  { code: "DZ", label: "Algérie" },
  { code: "DE", label: "Allemagne" },
  { code: "AD", label: "Andorre" },
  { code: "AO", label: "Angola" },
  { code: "AI", label: "Anguilla" },
  { code: "AG", label: "Antigua et Barbuda" },
  { code: "AN", label: "Antilles néerlandaises (Bonaire, Curaçao, Saba et St Eustache)" },
  { code: "SA", label: "Arabie Saoudite" },
  { code: "AR", label: "Argentine" },
  { code: "AM", label: "Arménie" },
  { code: "AW", label: "Aruba" },
  { code: "AU", label: "Australie" },
  { code: "AT", label: "Autriche" },
  { code: "AZ", label: "Azerbaïdjan" },
  { code: "BS", label: "Bahamas" },
  { code: "BH", label: "Bahrein" },
  { code: "BD", label: "Bangladesh" },
  { code: "BB", label: "Barbade" },
  { code: "BE", label: "Belgique" },
  { code: "BZ", label: "Belize" },
  { code: "BM", label: "Bermudes" },
  { code: "BT", label: "Bhoutan" },
  { code: "BO", label: "Bolivie" },
  { code: "BA", label: "Bosnie" },
  { code: "BW", label: "Botswana" },
  { code: "BN", label: "Brunei" },
  { code: "BR", label: "Brésil" },
  { code: "BG", label: "Bulgarie" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "BJ", label: "Bénin" },
  { code: "KH", label: "Cambodge" },
  { code: "CM", label: "Cameroun" },
  { code: "CA", label: "Canada" },
  { code: "CV", label: "Cap-Vert" },
  { code: "CL", label: "Chili" },
  { code: "CN", label: "Chine" },
  { code: "CY", label: "Chypre" },
  { code: "CO", label: "Colombie" },
  { code: "KM", label: "Comores" },
  { code: "CG", label: "Congo" },
  { code: "KR", label: "Corée du sud" },
  { code: "CR", label: "Costa Rica" },
  { code: "HR", label: "Croatie" },
  { code: "CU", label: "Cuba" },
  { code: "CI", label: "Côte d'Ivoire" },
  { code: "DK", label: "Danemark" },
  { code: "DJ", label: "Djibouti" },
  { code: "DM", label: "Dominique" },
  { code: "EG", label: "Egypte" },
  { code: "SV", label: "El Salvador" },
  { code: "EC", label: "Equateur" },
  { code: "ER", label: "Erythrée" },
  { code: "ES", label: "Espagne" },
  { code: "EE", label: "Estonie" },
  { code: "ET", label: "Ethiopie" },
  { code: "FJ", label: "Fidji" },
  { code: "FI", label: "Finlande" },
  { code: "GA", label: "Gabon" },
  { code: "GM", label: "Gambie" },
  { code: "GE", label: "Georgie" },
  { code: "GH", label: "Ghana" },
  { code: "GI", label: "Gibraltar" },
  { code: "GD", label: "Grenade" },
  { code: "GL", label: "Groenland" },
  { code: "GR", label: "Grèce" },
  { code: "GP", label: "Guadeloupe" },
  { code: "GU", label: "Guam" },
  { code: "GT", label: "Guatemala" },
  { code: "GS", label: "Guernesey" },
  { code: "GN", label: "Guinée" },
  { code: "GQ", label: "Guinée équatoriale" },
  { code: "GW", label: "Guinée-Bissau" },
  { code: "GY", label: "Guyana" },
  { code: "GF", label: "Guyane" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "HU", label: "Hongrie" },
  { code: "IN", label: "Inde" },
  { code: "ID", label: "Indonésie" },
  { code: "IQ", label: "Iraq" },
  { code: "IE", label: "Irlande" },
  { code: "IS", label: "Islande" },
  { code: "IL", label: "Israël" },
  { code: "IT", label: "Italie" },
  { code: "JM", label: "Jamaïque" },
  { code: "JP", label: "Japon" },
  { code: "JE", label: "Jersey" },
  { code: "JO", label: "Jordanie" },
  { code: "KZ", label: "Kazakhstan" },
  { code: "KE", label: "Kenya" },
  { code: "KG", label: "Kirghizistan" },
  { code: "KW", label: "Koweït" },
  { code: "LA", label: "Laos" },
  { code: "LS", label: "Lesotho" },
  { code: "LV", label: "Lettonie" },
  { code: "LB", label: "Liban" },
  { code: "LR", label: "Liberia" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lituanie" },
  { code: "LU", label: "Luxembourg" },
  { code: "MO", label: "Macao" },
  { code: "MK", label: "Macédoine" },
  { code: "MG", label: "Madagascar" },
  { code: "MY", label: "Malaisie" },
  { code: "MW", label: "Malawi" },
  { code: "MV", label: "Maldives" },
  { code: "ML", label: "Mali" },
  { code: "MT", label: "Malte" },
  { code: "MA", label: "Maroc" },
  { code: "MQ", label: "Martinique" },
  { code: "MR", label: "Mauritanie" },
  { code: "YT", label: "Mayotte" },
  { code: "MX", label: "Mexique" },
  { code: "FM", label: "Micronésie" },
  { code: "MD", label: "Moldavie" },
  { code: "MN", label: "Mongolie" },
  { code: "MS", label: "Montserrat" },
  { code: "ME", label: "Monténégro" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibie" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Niger" },
  { code: "NG", label: "Nigéria" },
  { code: "NO", label: "Norvège" },
  { code: "NC", label: "Nouvelle-Calédonie" },
  { code: "NZ", label: "Nouvelle-Zélande" },
  { code: "NP", label: "Népal" },
  { code: "OM", label: "Oman" },
  { code: "UG", label: "Ouganda" },
  { code: "UZ", label: "Ouzbékistan" },
  { code: "PK", label: "Pakistan" },
  { code: "PW", label: "Palaos" },
  { code: "PS", label: "Palestine" },
  { code: "PA", label: "Panama" },
  { code: "PG", label: "Papouasie Nouvelle Guinée" },
  { code: "PY", label: "Paraguay" },
  { code: "NL", label: "Pays-Bas" },
  { code: "PH", label: "Philippines" },
  { code: "PL", label: "Pologne" },
  { code: "PF", label: "Polynésie Française" },
  { code: "PR", label: "Porto Rico" },
  { code: "PT", label: "Portugal" },
  { code: "PE", label: "Pérou" },
  { code: "QA", label: "Qatar" },
  { code: "RO", label: "Roumanie" },
  { code: "GB", label: "Royaume-Uni" },
  { code: "RW", label: "Rwanda" },
  { code: "DO", label: "République Dominicaine" },
  { code: "CZ", label: "République Tchèque" },
  { code: "CD", label: "République démocratique du Congo" },
  { code: "RE", label: "Réunion" },
  { code: "BL", label: "Saint-Barthélémy" },
  { code: "KN", label: "Saint-Christophe-et-Niévès" },
  { code: "MI", label: "Saint-Martin (partie néerlandaise)" },
  { code: "MF", label: "Saint-Martin - Partie française" },
  { code: "PM", label: "Saint-Pierre-et-Miquelon" },
  { code: "VC", label: "Saint-Vincent-et-les-Grenadines" },
  { code: "LC", label: "Sainte-Lucie" },
  { code: "WS", label: "Samoa" },
  { code: "AS", label: "Samoa américaines" },
  { code: "SM", label: "San Marin" },
  { code: "ST", label: "Sao Tome et Principe" },
  { code: "RS", label: "Serbie" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leone" },
  { code: "SG", label: "Singapour" },
  { code: "SK", label: "Slovaquie" },
  { code: "SI", label: "Slovénie" },
  { code: "LK", label: "Sri Lanka" },
  { code: "CH", label: "Suisse" },
  { code: "SR", label: "Surinam" },
  { code: "SE", label: "Suède" },
  { code: "SZ", label: "Swaziland" },
  { code: "SN", label: "Sénégal" },
  { code: "TJ", label: "Tadjikistan" },
  { code: "TZ", label: "Tanzanie" },
  { code: "TW", label: "Taïwan" },
  { code: "TD", label: "Tchad" },
  { code: "TH", label: "Thaïlande" },
  { code: "TL", label: "Timor" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinité et Tobago" },
  { code: "TN", label: "Tunisie" },
  { code: "TR", label: "Turquie" },
  { code: "UY", label: "Uruguay" },
  { code: "VU", label: "Vanuatu" },
  { code: "VA", label: "Vatican" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "WF", label: "Wallis et Futuna" },
  { code: "ZM", label: "Zambie" },
  { code: "ZW", label: "Zimbabwe" },
  { code: "AE", label: "Émirats arabes unis" },
  { code: "US", label: "États-Unis" },
  { code: "CX", label: "Île Christmas" },
  { code: "MU", label: "Île Maurice" },
  { code: "NF", label: "Île Norfolk" },
  { code: "IC", label: "Îles Canaries" },
  { code: "KY", label: "Îles Caïmans" },
  { code: "CC", label: "Îles Cocos" },
  { code: "CK", label: "Îles Cook" },
  { code: "FO", label: "Îles Féroé" },
  { code: "MP", label: "Îles Mariannes du Nord" },
  { code: "MH", label: "Îles Marshall" },
  { code: "SB", label: "Îles Salomon" },
  { code: "TC", label: "Îles Turques-et-Caïques" },
  { code: "VI", label: "Îles Vierges américaines" },
  { code: "VG", label: "Îles Vierges britanniques" },
];

// Nom complet du pays (majuscules, cf. exemples Chronopost "FRANCE"/"BELGIQUE") à partir
// d'un code ISO2, pour renseigner recipientCountryName/shipperCountryName sur les
// étiquettes. Retombe sur le code lui-même si absent de la liste (pays hors zone
// livrable ou code déjà invalide en amont).
export function countryLabel(code: string): string {
  const match = COUNTRY_OPTIONS.find((c) => c.code === (code || "").toUpperCase());
  return match ? match.label.toUpperCase() : (code || "").toUpperCase();
}
